/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Link } from './link';


export interface EntityModelEmployee { 
    firstName?: string;
    lastName?: string;
    phone?: string;
    annualBalance?: number;
    unpaidBalance?: number;
    maternityBalance?: number;
    sickBalance?: number;
    salary?: number;
    userAccount?: User;
    poste?: string;
    id?: number;
    _links?: { [key: string]: Link; };
}

